// <auto-generated />
using System;
using FreelancerProfile.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FreelancerProfile.Infrastructure.Migrations
{
    [DbContext(typeof(FreelancerProfileContext))]
    partial class FreelancerProfileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FreelancerId");

                    b.ToTable("Certifications", (string)null);
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FreelancerId");

                    b.ToTable("Educations", (string)null);
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Employment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FreelancerId");

                    b.ToTable("Employments", (string)null);
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "English",
                            ShortName = "en"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Serbian",
                            ShortName = "sr"
                        },
                        new
                        {
                            Id = 3,
                            Name = "German",
                            ShortName = "de"
                        });
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.LanguageKnowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uuid");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfiencyLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FreelancerId");

                    b.HasIndex("LanguageId");

                    b.ToTable("LanguageKnowledges", (string)null);
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.PortfolioProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FreelancerId");

                    b.ToTable("PortfolioProjects", (string)null);
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Profession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Professions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6861f65-0950-4c7f-b5b1-de644f923fbb"),
                            Description = "Software engineer",
                            Name = "Software engineer"
                        },
                        new
                        {
                            Id = new Guid("5d9c0a7f-cf11-4c29-930a-0842fe6be2ad"),
                            Description = "Graphic designer",
                            Name = "Graphic designer"
                        });
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProfessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionId");

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4320c74f-4b82-4a54-abf7-6097fbfd0078"),
                            Description = "Programming language",
                            Name = "Java",
                            ProfessionId = new Guid("d6861f65-0950-4c7f-b5b1-de644f923fbb")
                        },
                        new
                        {
                            Id = new Guid("93098c08-85ff-4c31-994b-5dec79c17d79"),
                            Description = "Programming language",
                            Name = "C#",
                            ProfessionId = new Guid("d6861f65-0950-4c7f-b5b1-de644f923fbb")
                        },
                        new
                        {
                            Id = new Guid("ea1627e1-2d59-427d-b5b4-13ab7e944c7f"),
                            Description = "Web framework",
                            Name = "ASP>NET CORE",
                            ProfessionId = new Guid("d6861f65-0950-4c7f-b5b1-de644f923fbb")
                        },
                        new
                        {
                            Id = new Guid("39855c82-eb88-4794-b539-85407fbb59c5"),
                            Description = "Design software",
                            Name = "Adobe Illustrator",
                            ProfessionId = new Guid("5d9c0a7f-cf11-4c29-930a-0842fe6be2ad")
                        },
                        new
                        {
                            Id = new Guid("336dda85-0a33-42b8-a591-b18a29dbcaa6"),
                            Description = "Design software",
                            Name = "Adobe Photoshop",
                            ProfessionId = new Guid("5d9c0a7f-cf11-4c29-930a-0842fe6be2ad")
                        },
                        new
                        {
                            Id = new Guid("75b05ed6-9847-4564-ab1d-8f34acf657bc"),
                            Description = "Design software",
                            Name = "CorelDRAW Graphics Suite",
                            ProfessionId = new Guid("5d9c0a7f-cf11-4c29-930a-0842fe6be2ad")
                        });
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Freelancer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Availability")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsProfilePublic")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProfessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Freelancers", (string)null);
                });

            modelBuilder.Entity("FreelancerSkill", b =>
                {
                    b.Property<Guid>("FreelancersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("uuid");

                    b.HasKey("FreelancersId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("FreelancerSkill", (string)null);
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Certification", b =>
                {
                    b.HasOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Freelancer", null)
                        .WithMany("Certifications")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Certification.Attended#FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.ValueObjects.DateRange", "Attended", b1 =>
                        {
                            b1.Property<Guid>("CertificationId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("date");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date");

                            b1.HasKey("CertificationId");

                            b1.ToTable("Certifications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CertificationId");
                        });

                    b.Navigation("Attended")
                        .IsRequired();
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Education", b =>
                {
                    b.HasOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Freelancer", null)
                        .WithMany("Educations")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Education.Attended#FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.ValueObjects.DateRange", "Attended", b1 =>
                        {
                            b1.Property<Guid>("EducationId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("date");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date");

                            b1.HasKey("EducationId");

                            b1.ToTable("Educations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EducationId");
                        });

                    b.Navigation("Attended")
                        .IsRequired();
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Employment", b =>
                {
                    b.HasOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Freelancer", null)
                        .WithMany("Employments")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Employment.Period#FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.ValueObjects.DateRange", "Period", b1 =>
                        {
                            b1.Property<Guid>("EmploymentId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("date");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date");

                            b1.HasKey("EmploymentId");

                            b1.ToTable("Employments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmploymentId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.LanguageKnowledge", b =>
                {
                    b.HasOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Freelancer", null)
                        .WithMany("LanguageKnowledges")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.PortfolioProject", b =>
                {
                    b.HasOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Freelancer", null)
                        .WithMany("PortfolioProjects")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.PortfolioProject.Period#FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.ValueObjects.DateRange", "Period", b1 =>
                        {
                            b1.Property<Guid>("PortfolioProjectId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("date");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date");

                            b1.HasKey("PortfolioProjectId");

                            b1.ToTable("PortfolioProjects", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PortfolioProjectId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Skill", b =>
                {
                    b.HasOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Profession", "Profession")
                        .WithMany("Skills")
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Freelancer", b =>
                {
                    b.HasOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Freelancer.Contact#FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.ValueObjects.Contact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("FreelancerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FreelancerId");

                            b1.ToTable("Freelancers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FreelancerId");

                            b1.OwnsOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Freelancer.Contact#FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.ValueObjects.Contact.Address#FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("ContactFreelancerId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("ZipCode")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("ContactFreelancerId");

                                    b2.ToTable("Freelancers", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ContactFreelancerId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.OwnsOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Freelancer.HourlyRate#FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.ValueObjects.HourlyRate", "HourlyRate", b1 =>
                        {
                            b1.Property<Guid>("FreelancerId")
                                .HasColumnType("uuid");

                            b1.Property<float>("Amount")
                                .HasColumnType("real");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FreelancerId");

                            b1.ToTable("Freelancers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FreelancerId");
                        });

                    b.OwnsOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Freelancer.ProfileSummary#FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.ValueObjects.ProfileSummary", "ProfileSummary", b1 =>
                        {
                            b1.Property<Guid>("FreelancerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FreelancerId");

                            b1.ToTable("Freelancers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FreelancerId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("HourlyRate")
                        .IsRequired();

                    b.Navigation("Profession");

                    b.Navigation("ProfileSummary")
                        .IsRequired();
                });

            modelBuilder.Entity("FreelancerSkill", b =>
                {
                    b.HasOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Freelancer", null)
                        .WithMany()
                        .HasForeignKey("FreelancersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Entites.Profession", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("FreelancerProfile.Domain.AggregatesModel.FreelancerAggregate.Freelancer", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Educations");

                    b.Navigation("Employments");

                    b.Navigation("LanguageKnowledges");

                    b.Navigation("PortfolioProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
