version: '3.4'

services:
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    ports:
     - 50000:80

  jobmanagement.api:
    image: ${DOCKER_REGISTRY-}jobmanagementapi
    build:
      context: .
      dockerfile: src/Services/JobManagement/JobManagement.API/Dockerfile
    ports:
     - 51000:80

  profilemanagemenet.api:
    image: ${DOCKER_REGISTRY-}profilemanagemenetapi
    build:
      context: .
      dockerfile: src/Services/ProfileManagement/ProfileManagemenet.API/Dockerfile
    ports:
     - 52000:80
