name: "Build and test image"

inputs:
    service:
        description: "Service to build"
        required: true
    project_path:
        description: "Path to project to test"
        required: true
    tests_path:
        description: "Path to test project"
        required: true

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 6.0.x

        - name: Build and run integration tests
          shell: bash
          run: |
            cd server-side
            dotnet restore "FreelancePlatform.sln"
            cd ${{ inputs.project_path }}
            dotnet build --no-restore
            cd -
            cd ${{ inputs.tests_path }}
            dotnet build --no-restore
            dotnet test --no-build -v=normal

        - name: Compose build ${{ inputs.service }}
          shell: bash
          run: |
            cd server-side
            docker-compose build ${{ inputs.service }}
